depth = -999;
image_speed = 0.35;
player = obj_player1;
has_selectedoption = 0;
slider[0] = noone;
slider[1] = noone;
slider[2] = noone;
//Draw Surface
surface = noone;
color[0] = 0;
color[1] = 0;
color[2] = 0;
color[3] = 0;
color[4] = 0;
color[5] = 0;
color[6] = 0;
color[7] = 0;
color[8] = 0;
color[9] = 0;
color[10] = 0;
//Update Colors
//customupdate = false;
yi = 600;
palettename = "Palette 1"
image_idnex = 0;
showtext = true;
_draw_x = 480;
_draw_y = -64;
choosen = false;
_message = noone;
store_message[0] = "USE THE MOUSE TO DRAG THE SLIDERS"
store_message[1] = "PRESS LEFT AND RIGHT TO CHANGE\n WHICH CUSTOM PALETTE TO CHANGE"
store_message[2] = "CLICK ON THE TEXT BOX TO EDIT\n THE VALUES WITH A KEYBOARD"
store_message[3] = "PRESS UP AND DOWN TO CHANGE\n WHICH COLOR TO EDIT"
store_message[4] = "PRESS SLAP TO EXIT AND SAVE CHANGES"
_messageindex = 0;
alarm[1] = 50;
stop = false;
//Text Input
input = "Palette 0"
input_text = false
keyboard_string = ""
inputbuffer = 2
inputmax = 2
deletebuffer = 6
deletemax = 6
//Edit Cursor
cursor = "|";
delay = 20;
alarm[2] = delay;