if (image_index == 1 && global.panic == 0 && global.snickchallenge == 0)
{
    with (obj_player)
    {
        if (state == 61 && floor(image_index) == (image_number - 2))
        {
            scr_soundeffect(15)
            with (obj_player1)
            {
                sprite_index = spr_Timesup
                image_index = 0
                with (obj_camera)
                {
                    shake_mag = 10
                    shake_mag_acc = (30 / room_speed)
                }
            }
            if (global.coop == 1)
            {
                with (obj_player2)
                {
                    sprite_index = spr_Timesup
                    image_index = 0
                    with (obj_camera)
                    {
                        shake_mag = 10
                        shake_mag_acc = (30 / room_speed)
                    }
                }
            }
            other.image_index = 0
            ds_list_add(global.saveroom, other.id)
        }
    }
}
with (obj_player)
{
    if (grounded && x > (other.x - 160) && x < (other.x + 160) && key_up && (state == 0 || state == 69 || state == 70 || state == 91) && (global.panic == 1 || global.snickchallenge == 1))
    {
        if (global.timeattack == 1)
            obj_timeattack.stop = 1
        global.lapping = 0
        global.laptouched = 0
        targetDoor = "A"
        obj_camera.alarm[2] = -1
        scr_stopescapemusic()
        if ((global.collect) >= global.srank)
        {
            global.rank = "s"
            if (global.snickchallenge == 1)
                global.SAGEsnicksrank = 1
        }
        else if ((global.collect) > global.arank)
            global.rank = "a"
        else if ((global.collect) > global.brank)
            global.rank = "b"
        else if ((global.collect) > global.crank)
            global.rank = "c"
        else
            global.rank = "d"
        if (global.rank == "s")
            scr_soundeffect(82)
        if (global.rank == "a")
            scr_soundeffect(83)
        if (global.rank == "b")
            scr_soundeffect(85)
        if (global.rank == "c")
            scr_soundeffect(85)
        if (global.rank == "d")
            scr_soundeffect(86)
        
		#region Get Score
        ini_open("playerData_"+global.savefile+".ini")
        var roomname = room_get_name(room)	
        if (string_letters(roomname) == "entrance")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.entrancesecret)
                ini_write_string("Secret", "entrance", global.secretfound)
            if (global.entrancetreasure == 0)
                ini_write_string("Treasure", "entrance", global.treasure)
            if (global.entrancehighscore < global.collect)
                ini_write_string("Highscore", "entrance", global.collect)
            if (global.entrancehighscore < global.collect)
                ini_write_string("Highscore", "entrance", global.collect)
            if (global.entrancetoppin1 != 1)
                ini_write_string("Toppin", "entrance1", global.shroomfollow)
            if (global.entrancetoppin2 != 1)
                ini_write_string("Toppin", "entrance2", global.cheesefollow)
            if (global.entrancetoppin3 != 1)
                ini_write_string("Toppin", "entrance3", global.tomatofollow)
            if (global.entrancetoppin4 != 1)
                ini_write_string("Toppin", "entrance4", global.sausagefollow)
            if (global.entrancetoppin5 != 1)
                ini_write_string("Toppin", "entrance5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "entrance", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "entrance", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "entrance", "none") && "a" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "entrance", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "entrance", "none") && "a" != ini_read_string("Ranks", "entrance", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "entrance", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "entrance", "none") && "a" != ini_read_string("Ranks", "entrance", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "entrance", global.rank)
        }
        if (string_letters(roomname) == "medieval")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.SAGEknighttaken == 0)
            {
                global.SAGEknight = 1
                global.SAGEknight = ini_write_string("SAGE2019", "knight", 1)
            }
            if (global.secretfound > global.medievalsecret)
                ini_write_string("Secret", "medieval", global.secretfound)
            if (global.medievaltreasure == 0)
                ini_write_string("Treasure", "medieval", global.treasure)
            if (global.medievalhighscore < global.collect)
                ini_write_string("Highscore", "medieval", global.collect)
            if (global.medievalhighscore < global.collect)
                ini_write_string("Highscore", "medieval", global.collect)
            if (global.medievaltoppin1 != 1)
                ini_write_string("Toppin", "medieval1", global.shroomfollow)
            if (global.medievaltoppin2 != 1)
                ini_write_string("Toppin", "medieval2", global.cheesefollow)
            if (global.medievaltoppin3 != 1)
                ini_write_string("Toppin", "medieval3", global.tomatofollow)
            if (global.medievaltoppin4 != 1)
                ini_write_string("Toppin", "medieval4", global.sausagefollow)
            if (global.medievaltoppin5 != 1)
                ini_write_string("Toppin", "medieval5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "medieval", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "medieval", "none"))
                ini_write_string("Ranks", "medieval", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "medieval", "none") && "a" != ini_read_string("Ranks", "medieval", "none"))
                ini_write_string("Ranks", "medieval", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "medieval", "none") && "a" != ini_read_string("Ranks", "medieval", "none") && "b" != ini_read_string("Ranks", "medieval", "none"))
                ini_write_string("Ranks", "medieval", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "medieval", "none") && "a" != ini_read_string("Ranks", "medieval", "none") && "b" != ini_read_string("Ranks", "medieval", "none") && "c" != ini_read_string("Ranks", "medieval", "none"))
                ini_write_string("Ranks", "medieval", global.rank)
        }
        if (string_letters(roomname) == "chateau")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.chateausecret)
                ini_write_string("Secret", "chateau", global.secretfound)
            if (global.chateautreasure == 0)
                ini_write_string("Treasure", "chateau", global.treasure)
            if (global.chateauhighscore < global.collect)
                ini_write_string("Highscore", "chateau", global.collect)
            if (global.chateauhighscore < global.collect)
                ini_write_string("Highscore", "chateau", global.collect)
            if (global.chateautoppin1 != 1)
                ini_write_string("Toppin", "chateau1", global.shroomfollow)
            if (global.chateautoppin2 != 1)
                ini_write_string("Toppin", "chateau2", global.cheesefollow)
            if (global.chateautoppin3 != 1)
                ini_write_string("Toppin", "chateau3", global.tomatofollow)
            if (global.chateautoppin4 != 1)
                ini_write_string("Toppin", "chateau4", global.sausagefollow)
            if (global.chateautoppin5 != 1)
                ini_write_string("Toppin", "chateau5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "chateau", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "chateau", "none"))
                ini_write_string("Ranks", "chateau", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "chateau", "none") && "a" != ini_read_string("Ranks", "chateau", "none"))
                ini_write_string("Ranks", "chateau", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "chateau", "none") && "a" != ini_read_string("Ranks", "chateau", "none") && "b" != ini_read_string("Ranks", "chateau", "none"))
                ini_write_string("Ranks", "chateau", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "chateau", "none") && "a" != ini_read_string("Ranks", "chateau", "none") && "b" != ini_read_string("Ranks", "chateau", "none") && "c" != ini_read_string("Ranks", "chateau", "none"))
                ini_write_string("Ranks", "chateau", global.rank)
        }
        if (string_letters(roomname) == "ruin")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.ruinsecret)
                ini_write_string("Secret", "ruin", global.secretfound)
            if (global.ruintreasure == 0)
                ini_write_string("Treasure", "ruin", global.treasure)
            if (global.ruinhighscore < global.collect)
                ini_write_string("Highscore", "ruin", global.collect)
            if (global.ruinhighscore < global.collect)
                ini_write_string("Highscore", "ruin", global.collect)
            if (global.ruintoppin1 != 1)
                ini_write_string("Toppin", "ruin1", global.shroomfollow)
            if (global.ruintoppin2 != 1)
                ini_write_string("Toppin", "ruin2", global.cheesefollow)
            if (global.ruintoppin3 != 1)
                ini_write_string("Toppin", "ruin3", global.tomatofollow)
            if (global.ruintoppin4 != 1)
                ini_write_string("Toppin", "ruin4", global.sausagefollow)
            if (global.ruintoppin5 != 1)
                ini_write_string("Toppin", "ruin5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "ruin", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "ruin", "none"))
                ini_write_string("Ranks", "ruin", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "ruin", "none") && "a" != ini_read_string("Ranks", "ruin", "none"))
                ini_write_string("Ranks", "ruin", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "ruin", "none") && "a" != ini_read_string("Ranks", "ruin", "none") && "b" != ini_read_string("Ranks", "ruin", "none"))
                ini_write_string("Ranks", "ruin", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "ruin", "none") && "a" != ini_read_string("Ranks", "ruin", "none") && "b" != ini_read_string("Ranks", "ruin", "none") && "c" != ini_read_string("Ranks", "ruin", "none"))
                ini_write_string("Ranks", "ruin", global.rank)
        }
        if (string_letters(roomname) == "dungeon")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (obj_player.backupweapon == 1)
            {
                ini_write_string("SAGE2019", "dungeonbackup", 1)
                global.SAGEdungeonbackup = 1
            }
            if (global.secretfound > global.dungeonsecret)
                ini_write_string("Secret", "dungeon", global.secretfound)
            if (global.dungeontreasure == 0)
                ini_write_string("Treasure", "dungeon", global.treasure)
            if (global.dungeonhighscore < global.collect)
                ini_write_string("Highscore", "dungeon", global.collect)
            if (global.dungeonhighscore < global.collect)
                ini_write_string("Highscore", "dungeon", global.collect)
            if (global.dungeontoppin1 != 1)
                ini_write_string("Toppin", "dungeon1", global.shroomfollow)
            if (global.dungeontoppin2 != 1)
                ini_write_string("Toppin", "dungeon2", global.cheesefollow)
            if (global.dungeontoppin3 != 1)
                ini_write_string("Toppin", "dungeon3", global.tomatofollow)
            if (global.dungeontoppin4 != 1)
                ini_write_string("Toppin", "dungeon4", global.sausagefollow)
            if (global.dungeontoppin5 != 1)
                ini_write_string("Toppin", "dungeon5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "dungeon", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "dungeon", "none"))
                ini_write_string("Ranks", "dungeon", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "dungeon", "none") && "a" != ini_read_string("Ranks", "dungeon", "none"))
                ini_write_string("Ranks", "dungeon", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "dungeon", "none") && "a" != ini_read_string("Ranks", "dungeon", "none") && "b" != ini_read_string("Ranks", "dungeon", "none"))
                ini_write_string("Ranks", "dungeon", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "dungeon", "none") && "a" != ini_read_string("Ranks", "dungeon", "none") && "b" != ini_read_string("Ranks", "dungeon", "none") && "c" != ini_read_string("Ranks", "dungeon", "none"))
                ini_write_string("Ranks", "dungeon", global.rank)
        }
        if (room == strongcold_escape)
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.strongcoldsecret)
                ini_write_string("Secret", "strongcold", global.secretfound)
            if (global.strongcoldtreasure == 0)
                ini_write_string("Treasure", "strongcold", global.treasure)
            if (global.strongcoldhighscore < global.collect && global.timeattack == 0)
                ini_write_string("Highscore", "strongcold", global.collect)
            if (global.strongcoldtoppin1 != 1)
                ini_write_string("Toppin", "strongcold1", global.shroomfollow)
            if (global.strongcoldtoppin2 != 1)
                ini_write_string("Toppin", "strongcold2", global.cheesefollow)
            if (global.strongcoldtoppin3 != 1)
                ini_write_string("Toppin", "strongcold3", global.tomatofollow)
            if (global.strongcoldtoppin4 != 1)
                ini_write_string("Toppin", "strongcold4", global.sausagefollow)
            if (global.strongcoldtoppin5 != 1)
                ini_write_string("Toppin", "strongcold5", global.pineapplefollow)
            if (global.timeattack == 0)
            {
                if (global.rank == "s")
                    ini_write_string("Ranks", "strongcold", global.rank)
                if (global.rank == "a" && "s" != ini_read_string("Ranks", "strongcold", "none"))
                    ini_write_string("Ranks", "strongcold", global.rank)
                if (global.rank == "b" && "s" != ini_read_string("Ranks", "strongcold", "none") && "a" != ini_read_string("Ranks", "strongcold", "none"))
                    ini_write_string("Ranks", "strongcold", global.rank)
                if (global.rank == "c" && "s" != ini_read_string("Ranks", "strongcold", "none") && "a" != ini_read_string("Ranks", "strongcold", "none") && "b" != ini_read_string("Ranks", "strongcold", "none"))
                    ini_write_string("Ranks", "strongcold", global.rank)
                if (global.rank == "d" && "s" != ini_read_string("Ranks", "strongcold", "none") && "a" != ini_read_string("Ranks", "strongcold", "none") && "b" != ini_read_string("Ranks", "strongcold", "none") && "c" != ini_read_string("Ranks", "strongcold", "none"))
                    ini_write_string("Ranks", "strongcold", global.rank)
            }
            if (global.timeattack == 1)
            {
                if (global.rank == "s")
                    ini_write_string("Time", "strongcold", global.rank)
                if (global.rank == "a" && "s" != ini_read_string("Time", "strongcold", "none"))
                    ini_write_string("Time", "strongcold", global.rank)
                if (global.rank == "b" && "s" != ini_read_string("Time", "strongcold", "none") && "a" != ini_read_string("Time", "strongcold", "none"))
                    ini_write_string("Time", "strongcold", global.rank)
                if (global.rank == "c" && "s" != ini_read_string("Time", "strongcold", "none") && "a" != ini_read_string("Time", "strongcold", "none") && "b" != ini_read_string("Time", "strongcold", "none"))
                    ini_write_string("Time", "strongcold", global.rank)
                if (global.rank == "d" && "s" != ini_read_string("Time", "strongcold", "none") && "a" != ini_read_string("Time", "strongcold", "none") && "b" != ini_read_string("Time", "strongcold", "none") && "c" != ini_read_string("Time", "strongcold", "none"))
                    ini_write_string("Time", "strongcold", global.rank)
            }
        }
        if (string_letters(roomname) == "snickchallengeend")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.SAGEshotgunsnicknumber >= 6)
            {
                global.SAGEshotgunsnick = 1
                ini_write_string("SAGE2019", "shotgunsnick", 1)
            }
            if (global.snickchallengehighscore < global.collect)
                ini_write_string("Highscore", "snickchallenge", global.collect)
            if (global.snickchallengehighscore < global.collect)
                ini_write_string("Highscore", "snickchallenge", global.collect)
            if (global.rank == "s")
                ini_write_string("Ranks", "snickchallenge", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "snickchallenge", "none"))
                ini_write_string("Ranks", "snickchallenge", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "snickchallenge", "none") && "a" != ini_read_string("Ranks", "snickchallenge", "none"))
                ini_write_string("Ranks", "snickchallenge", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "snickchallenge", "none") && "a" != ini_read_string("Ranks", "snickchallenge", "none") && "b" != ini_read_string("Ranks", "snickchallenge", "none"))
                ini_write_string("Ranks", "snickchallenge", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "snickchallenge", "none") && "a" != ini_read_string("Ranks", "snickchallenge", "none") && "b" != ini_read_string("Ranks", "snickchallenge", "none") && "c" != ini_read_string("Ranks", "snickchallenge", "none"))
                ini_write_string("Ranks", "snickchallenge", global.rank)
            ini_close()
        }
        if (string_letters(roomname) == "desert")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.desertsecret)
                ini_write_string("Secret", "desert", global.secretfound)
            if (global.deserttreasure == 0)
                ini_write_string("Treasure", "desert", global.treasure)
            if (global.deserthighscore < global.collect)
                ini_write_string("Highscore", "desert", global.collect)
            if (global.deserthighscore < global.collect)
                ini_write_string("Highscore", "desert", global.collect)
            if (global.deserttoppin1 != 1)
                ini_write_string("Toppin", "desert1", global.shroomfollow)
            if (global.deserttoppin2 != 1)
                ini_write_string("Toppin", "desert2", global.cheesefollow)
            if (global.deserttoppin3 != 1)
                ini_write_string("Toppin", "desert3", global.tomatofollow)
            if (global.deserttoppin4 != 1)
                ini_write_string("Toppin", "desert4", global.sausagefollow)
            if (global.deserttoppin5 != 1)
                ini_write_string("Toppin", "desert5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "desert", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "desert", "none"))
                ini_write_string("Ranks", "desert", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "desert", "none") && "a" != ini_read_string("Ranks", "desert", "none"))
                ini_write_string("Ranks", "desert", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "desert", "none") && "a" != ini_read_string("Ranks", "desert", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "desert", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "desert", "none") && "a" != ini_read_string("Ranks", "desert", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "desert", global.rank)
        }
        if (string_letters(roomname) == "factory")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.factorysecret)
                ini_write_string("Secret", "factory", global.secretfound)
            if (global.factorytreasure == 0)
                ini_write_string("Treasure", "factory", global.treasure)
            if (global.factoryhighscore < global.collect)
                ini_write_string("Highscore", "factory", global.collect)
            if (global.factoryhighscore < global.collect)
                ini_write_string("Highscore", "factory", global.collect)
            if (global.factorytoppin1 != 1)
                ini_write_string("Toppin", "factory1", global.shroomfollow)
            if (global.factorytoppin2 != 1)
                ini_write_string("Toppin", "factory2", global.cheesefollow)
            if (global.factorytoppin3 != 1)
                ini_write_string("Toppin", "factory3", global.tomatofollow)
            if (global.factorytoppin4 != 1)
                ini_write_string("Toppin", "factory4", global.sausagefollow)
            if (global.factorytoppin5 != 1)
                ini_write_string("Toppin", "factory5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "factory", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "factory", "none"))
                ini_write_string("Ranks", "factory", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "factory", "none") && "a" != ini_read_string("Ranks", "factory", "none"))
                ini_write_string("Ranks", "factory", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "factory", "none") && "a" != ini_read_string("Ranks", "factory", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "factory", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "factory", "none") && "a" != ini_read_string("Ranks", "factory", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "factory", global.rank)
        }
        if (string_letters(roomname) == "sewer")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.sewersecret)
                ini_write_string("Secret", "sewer", global.secretfound)
            if (global.sewertreasure == 0)
                ini_write_string("Treasure", "sewer", global.treasure)
            if (global.sewerhighscore < global.collect)
                ini_write_string("Highscore", "sewer", global.collect)
            if (global.sewerhighscore < global.collect)
                ini_write_string("Highscore", "sewer", global.collect)
            if (global.sewertoppin1 != 1)
                ini_write_string("Toppin", "sewer1", global.shroomfollow)
            if (global.sewertoppin2 != 1)
                ini_write_string("Toppin", "sewer2", global.cheesefollow)
            if (global.sewertoppin3 != 1)
                ini_write_string("Toppin", "sewer3", global.tomatofollow)
            if (global.sewertoppin4 != 1)
                ini_write_string("Toppin", "sewer4", global.sausagefollow)
            if (global.sewertoppin5 != 1)
                ini_write_string("Toppin", "sewer5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "sewer", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "sewer", "none"))
                ini_write_string("Ranks", "sewer", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "sewer", "none") && "a" != ini_read_string("Ranks", "sewer", "none"))
                ini_write_string("Ranks", "sewer", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "sewer", "none") && "a" != ini_read_string("Ranks", "sewer", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "sewer", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "sewer", "none") && "a" != ini_read_string("Ranks", "sewer", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "sewer", global.rank)
        }
        if (string_letters(roomname) == "freezer")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.freezersecret)
                ini_write_string("Secret", "freezer", global.secretfound)
            if (global.freezertreasure == 0)
                ini_write_string("Treasure", "freezer", global.treasure)
            if (global.freezerhighscore < global.collect)
                ini_write_string("Highscore", "freezer", global.collect)
            if (global.freezerhighscore < global.collect)
                ini_write_string("Highscore", "freezer", global.collect)
            if (global.freezertoppin1 != 1)
                ini_write_string("Toppin", "freezer1", global.shroomfollow)
            if (global.freezertoppin2 != 1)
                ini_write_string("Toppin", "freezer2", global.cheesefollow)
            if (global.freezertoppin3 != 1)
                ini_write_string("Toppin", "freezer3", global.tomatofollow)
            if (global.freezertoppin4 != 1)
                ini_write_string("Toppin", "freezer4", global.sausagefollow)
            if (global.freezertoppin5 != 1)
                ini_write_string("Toppin", "freezer5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "freezer", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "freezer", "none"))
                ini_write_string("Ranks", "freezer", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "freezer", "none") && "a" != ini_read_string("Ranks", "freezer", "none"))
                ini_write_string("Ranks", "freezer", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "freezer", "none") && "a" != ini_read_string("Ranks", "freezer", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "freezer", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "freezer", "none") && "a" != ini_read_string("Ranks", "freezer", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "freezer", global.rank)
        }
        if (string_letters(roomname) == "mansion")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.mansionsecret)
                ini_write_string("Secret", "mansion", global.secretfound)
            if (global.mansiontreasure == 0)
                ini_write_string("Treasure", "mansion", global.treasure)
            if (global.mansionhighscore < global.collect)
                ini_write_string("Highscore", "mansion", global.collect)
            if (global.mansionhighscore < global.collect)
                ini_write_string("Highscore", "mansion", global.collect)
            if (global.mansiontoppin1 != 1)
                ini_write_string("Toppin", "mansion1", global.shroomfollow)
            if (global.mansiontoppin2 != 1)
                ini_write_string("Toppin", "mansion2", global.cheesefollow)
            if (global.mansiontoppin3 != 1)
                ini_write_string("Toppin", "mansion3", global.tomatofollow)
            if (global.mansiontoppin4 != 1)
                ini_write_string("Toppin", "mansion4", global.sausagefollow)
            if (global.mansiontoppin5 != 1)
                ini_write_string("Toppin", "mansion5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "mansion", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "mansion", "none"))
                ini_write_string("Ranks", "mansion", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "mansion", "none") && "a" != ini_read_string("Ranks", "mansion", "none"))
                ini_write_string("Ranks", "mansion", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "mansion", "none") && "a" != ini_read_string("Ranks", "mansion", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "mansion", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "mansion", "none") && "a" != ini_read_string("Ranks", "mansion", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "mansion", global.rank)
        }
        if (string_letters(roomname) == "golf")
        {
            ini_open("playerData_"+global.savefile+".ini")
            if (global.secretfound > global.golfsecret)
                ini_write_string("Secret", "golf", global.secretfound)
            if (global.golftreasure == 0)
                ini_write_string("Treasure", "golf", global.treasure)
            if (global.golfhighscore < global.collect)
                ini_write_string("Highscore", "golf", global.collect)
            if (global.golfhighscore < global.collect)
                ini_write_string("Highscore", "golf", global.collect)
            if (global.golftoppin1 != 1)
                ini_write_string("Toppin", "golf1", global.shroomfollow)
            if (global.golftoppin2 != 1)
                ini_write_string("Toppin", "golf2", global.cheesefollow)
            if (global.golftoppin3 != 1)
                ini_write_string("Toppin", "golf3", global.tomatofollow)
            if (global.golftoppin4 != 1)
                ini_write_string("Toppin", "golf4", global.sausagefollow)
            if (global.golftoppin5 != 1)
                ini_write_string("Toppin", "golf5", global.pineapplefollow)
            if (global.rank == "s")
                ini_write_string("Ranks", "golf", global.rank)
            if (global.rank == "a" && "s" != ini_read_string("Ranks", "golf", "none"))
                ini_write_string("Ranks", "golf", global.rank)
            if (global.rank == "b" && "s" != ini_read_string("Ranks", "golf", "none") && "a" != ini_read_string("Ranks", "golf", "none"))
                ini_write_string("Ranks", "golf", global.rank)
            if (global.rank == "c" && "s" != ini_read_string("Ranks", "golf", "none") && "a" != ini_read_string("Ranks", "golf", "none") && "b" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "golf", global.rank)
            if (global.rank == "d" && "s" != ini_read_string("Ranks", "golf", "none") && "a" != ini_read_string("Ranks", "golf", "none") && "b" != ini_read_string("Ranks", "entrance", "none") && "c" != ini_read_string("Ranks", "entrance", "none"))
                ini_write_string("Ranks", "golf", global.rank)
        }
        ini_close()
		#endregion
        if (!instance_exists(obj_endlevelfade))
            instance_create(x, y, obj_endlevelfade)
        if (!instance_exists(obj_gatetransition))
            instance_create(other.x, other.y, obj_gatetransition)
        obj_player1.state = 78
        obj_player1.sprite_index = obj_player1.spr_lookdoor
        if instance_exists(obj_player2)
        {
            obj_player2.state = 78
            obj_player2.sprite_index = obj_player2.spr_lookdoor
        }
        obj_endlevelfade.alarm[0] = 510
        image_index = 0
        global.panic = 0
        global.snickchallenge = 0
		global.fakepeppino = 0
    }
}


