var _cam_x = camera_get_view_x(view_camera[0])
var _cam_y = camera_get_view_y(view_camera[0])
var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
var lay_id4 = layer_get_id("Backgrounds_sky")
var back_id4 = layer_background_get_id(lay_id4)
var lay_id5 = layer_get_id("Backgrounds_sky2")
var back_id5 = layer_background_get_id(lay_id5)
var lay_id6 = layer_get_id("Backgrounds_far1")
var back_id6 = layer_background_get_id(lay_id6)
var lay_id7 = layer_get_id("Backgrounds_Ground1")
var back_id7 = layer_background_get_id(lay_id7)
var lay_id8 = layer_get_id("Backgrounds_Ground2")
var back_id8 = layer_background_get_id(lay_id8)
var lay_id9 = layer_get_id("Backgrounds_scroll")
var back_id9 = layer_background_get_id(lay_id9)
var lay_id10 = layer_get_id("Backgrounds_far")
var back_id10 = layer_background_get_id(lay_id10)
if (room != hub_room1 && room != hub_room3  && room != hub_room2 && room != cowboytask && obj_pause.pause == 0)
    global.scrolloffset += 1
    x_shift_1 += layer_get_hspeed("Backgrounds_sky")
    y_shift_1 += layer_get_vspeed("Backgrounds_sky")
    x_shift_2 += layer_get_hspeed("Backgrounds_sky2")
    y_shift_2 += layer_get_vspeed("Backgrounds_sky2")
    x_shift_3 += layer_get_hspeed("Backgrounds_scroll")
    y_shift_3 += layer_get_vspeed("Backgrounds_scroll")
layer_x("Backgrounds_scroll", (((_cam_x * 0.25) + x_shift_3) + (scrolloffset * layer_get_hspeed("Backgrounds_scroll"))))
layer_y("Backgrounds_scroll", (((_cam_y * 0.25) + y_shift_3) + (scrolloffset * layer_get_vspeed("Backgrounds_scroll"))))
layer_x("Backgrounds_1", (_cam_x * 0.25))
layer_y("Backgrounds_1", (_cam_y * 0.25))
layer_x("Backgrounds_2", (_cam_x * 0.15))
layer_y("Backgrounds_2", (_cam_y * 0.15))
layer_x("Backgrounds_3", (_cam_x * 0.05))
layer_y("Backgrounds_3", (_cam_y * 0.05))
layer_x("Backgrounds_Ground1", (_cam_x * 0.15))
layer_y("Backgrounds_Ground1", ((_cam_y * 0.15) + groundy))
layer_x("Backgrounds_Ground2", (_cam_x * 0.25))
layer_y("Backgrounds_Ground2", ((_cam_y * 0.25) + ground2y))
layer_x("Backgrounds_sky", (((_cam_x * 0.15) + x_shift_1) + (scrolloffset * layer_get_hspeed("Backgrounds_sky"))))
layer_y("Backgrounds_sky", (((_cam_y * 0.15) + y_shift_1) + (scrolloffset * layer_get_vspeed("Backgrounds_sky"))))
layer_x("Backgrounds_sky2", (((_cam_x * 0.05) + x_shift_2) + (scrolloffset * layer_get_hspeed("Backgrounds_sky2"))))
layer_y("Backgrounds_sky2", (((_cam_y * 0.05) + y_shift_2) + (scrolloffset * layer_get_vspeed("Backgrounds_sky2"))))
layer_x("Backgrounds_far1",(_cam_x - clamp(_cam_x * 0.25 * (960 / room_width), 0, (sprite_get_width(layer_background_get_sprite(back_id6)) - 960   ) )))
layer_y("Backgrounds_far1",(_cam_y - clamp(_cam_y * 0.25 * (540 / room_height), 0, (sprite_get_height(layer_background_get_sprite(back_id6)) - 540 ) )))
layer_x("Backgrounds_far", (_cam_x - clamp(_cam_x * 0.3 * (960 / room_width), 0, (sprite_get_width(layer_background_get_sprite(back_id10))  - 960) )))
layer_y("Backgrounds_far", (_cam_y - clamp(_cam_y * 0.3 * (540 / room_height), 0, (sprite_get_height(layer_background_get_sprite(back_id10)) - 540 ) )))


