function scr_panicbg_start() {
	if ((!variable_global_exists("panicbg_surface")) || (!surface_exists(global.panicbg_surface)))
	    global.panicbg_surface = surface_create(camera_get_view_width(view_camera[0]) + 128, camera_get_view_height(view_camera[0]) + 128)
	if event_type == ev_draw and event_number == 0
	{
	    surface_set_target(global.panicbg_surface)
	    draw_clear_alpha(c_black, 0)
	    var _cam_x = camera_get_view_x(view_camera[0])
	    var _cam_y = camera_get_view_y(view_camera[0])
	    var bg1 = layer_get_id("Backgrounds_1")
	    var bg2 = layer_get_id("Backgrounds_2")
	    var bg3 = layer_get_id("Backgrounds_3")
	    var bg4 = layer_get_id("Backgrounds_sky")
	    var bg5 = layer_get_id("Backgrounds_sky2")
	    var bg6 = layer_get_id("Backgrounds_Ground1")
	    var bg7 = layer_get_id("Backgrounds_Ground2")
	    var bg8 = layer_get_id("Backgrounds_far1")
	    var bg9 = layer_get_id("Backgrounds_scroll")
		var bg10 = layer_get_id("Backgrounds_far")
		var bg11 = layer_get_id("Backgrounds_4")	
		var bg12 = layer_get_id("Backgrounds_long")	
	    var bg13 = layer_get_id("Backgrounds_H1")
	    var bg14 = layer_get_id("Backgrounds_H2")	
		var bg15 = layer_get_id("Backgrounds_long2")	
	    layer_x(bg1, ((layer_get_x(bg1) - _cam_x) + 64))
	    layer_y(bg1, ((layer_get_y(bg1) - _cam_y) + 64))
	    layer_x(bg2, ((layer_get_x(bg2) - _cam_x) + 64))
	    layer_y(bg2, ((layer_get_y(bg2) - _cam_y) + 64))
	    layer_x(bg3, ((layer_get_x(bg3) - _cam_x) + 64))
	    layer_y(bg3, ((layer_get_y(bg3) - _cam_y) + 64))
	    layer_x(bg4, ((layer_get_x(bg4) - _cam_x) + 64))
	    layer_y(bg4, ((layer_get_y(bg4) - _cam_y) + 64))
	    layer_x(bg5, ((layer_get_x(bg5) - _cam_x) + 64))
	    layer_y(bg5, ((layer_get_y(bg5) - _cam_y) + 64))
	    layer_x(bg6, ((layer_get_x(bg6) - _cam_x) + 64))
	    layer_y(bg6, ((layer_get_y(bg6) - _cam_y) + 64))
	    layer_x(bg7, ((layer_get_x(bg7) - _cam_x) + 64))
	    layer_y(bg7, ((layer_get_y(bg7) - _cam_y) + 64))
	    layer_x(bg8, ((layer_get_x(bg8) - _cam_x) + 64))
	    layer_y(bg8, ((layer_get_y(bg8) - _cam_y) + 64))
	    layer_x(bg9, ((layer_get_x(bg9) - _cam_x) + 64))
	    layer_y(bg9, ((layer_get_y(bg9) - _cam_y) + 64))
		layer_x(bg10, ((layer_get_x(bg10) - _cam_x) + 64))	
		layer_y(bg10, ((layer_get_y(bg10) - _cam_y) + 64))
	    layer_x(bg11, ((layer_get_x(bg11) - _cam_x) + 64))
	    layer_y(bg11, ((layer_get_y(bg11) - _cam_y) + 64))	
	    layer_x(bg12, ((layer_get_x(bg12) - _cam_x) + 64))
	    layer_y(bg12, ((layer_get_y(bg12) - _cam_y) + 64))	
	
	    layer_x(bg13, ((layer_get_x(bg13) - _cam_x) + 64))
	    layer_y(bg13, ((layer_get_y(bg13) - _cam_y) + 64))
	    layer_x(bg14, ((layer_get_x(bg14) - _cam_x) + 64))
	    layer_y(bg14, ((layer_get_y(bg14) - _cam_y) + 64))	
		
	    layer_x(bg15, ((layer_get_x(bg15) - _cam_x) + 64))
	    layer_y(bg15, ((layer_get_y(bg15) - _cam_y) + 64))			
	}



}