gpu_set_fog(true, image_blend, 0, 1000)
draw_set_alpha(image_alpha)
draw_sprite_ext(sprite_index, image_index, x, y, image_xscale, image_yscale, image_angle, c_white, image_alpha)
draw_set_alpha(1)
gpu_set_fog(false, c_white, 0, 1000)